config/routes.rb
Spree::Core::Engine.routes.draw do
   Spree::Core::Engine.add_routes do
    resources :contacts
    get :address
    put :address
  end
end

app/controllers/spree/contacts_controller.rb
module Spree
  class ContactsController < Spree::StoreController
  
   def index
     @contacts = Spree::Contact.all
   end
   
   def show
     @contact = Spree::Contact.find(params[:id])
   end
   
   def new
     @contact =Spree::Contact.new
      @sexs = ["male" ,"female"]
   end
   
   def create
    @contact = Spree::Contact.new(contact_params)
     @sexs = ["male" ,"female"]
    if @contact.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end
   end
   
   def edit
     @contact = Spree::Contact.find(params[:id])
    @sexs = ["male" ,"female"]
   end
   
   def update
    @contact = Spree::Contact.find(params[:id])
    @sexs = ["male" ,"female"]
    if @contact.update_attributes(contact_param)
      redirect_to :action => 'show', :id => @contact
    else
      render :action => 'edit'
    end
   end
   
   def delete
      Spree::Contact.find(params[:id]).destroy
      redirect_to :action => 'index'
   end
    
   def contact_params
    params.require(:contact).permit(:name, :birthday, :sex, :email,  :address,  :relationship, :contactimage)
   end
     
  end
end

app/views/spree/contacts/index.html.erb
<div class="container">
 <div class="ScrollStyle">
 <div class=row style="width:500px;margin-left: 250px;">
     
 <div class="col-md-4" >
     <p class="circle">&#10010;</p>
     <p align="center" style=" margin-left: -30px;"><%= link_to "Add User", {:action => 'new' }%></p>
 <% @contacts.each do |f| %>
 </div>
  <div class="col-md-4" style="margin-bottom: 25px;">
 <p class="round-image-75"> <%= image_tag(f.contactimage) %></p>
   <b><%= f.name %><br></b>
    <%= f.relationship %><br>
 <% end %>
  </div>
</div>
</div>
<br><br>




</div>

app/views/spree/contacts/new.html.erb
<div style="width:500px;margin-left: 250px;">
<h1> Add Contact Details </h1>


<%= form_for @contact do |f| %>
 
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control'  %>
  </div>
  
  <div class="form-group">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :sex %><br>
    <%= f.select :sex, options_for_select(@sexs),class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_area :address, class: 'form-control' %>
  </div> 
 
  <div class="form-group">
    <%= f.label :relationship %><br>
    <%= f.text_field :relationship, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :contactimage %>
  </div>
  
  <div class="form-group">
   <%= render :partial => 'spree/address/form', :locals => { :form => ship_form, :address_type => 'shipping', :address => @order.ship_address } %>
  </div>
 
  <div class="circle">
    <%= f.submit  "Save Contact", class: "btn btn-primary"  %>
  </div>
  
  <div class="circle" style="margin-top: -100px; margin-left: 250px;color: black;">
    <h4 style="margin-top: 25px;"> Invite Contacts</h4>
  </div>
<% end %>
</div>
<%#= link_to 'Back', {:action => 'contact'} %>

app/views/spree/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>


<p>
  <strong>Birthday:</strong>
  <%= @contact.birthday %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @contact.sex %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

 
<p>
  <strong>Address:</strong>
  <%= @contact.address %>
</p>

<p>
  <strong>Relationship:</strong>
  <%= @contact.relationship %>
</p>

<p class="round-image-50">
  <strong>ContactImage:</strong>
<%= image_tag @contact.contactimage.url %>
</p>

<%= link_to 'Back', contacts_path %>